set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")

set(MISTRAL_ARCH "aarch64-none-elf" CACHE STRING "Target architecture")

set(CMAKE_C_COMPILER ${TOOLCHAIN_PATH}${MISTRAL_ARCH}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PATH}${MISTRAL_ARCH}-g++)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PATH}${MISTRAL_ARCH}-gcc)
set(CMAKE_OBJCOPY ${TOOLCHAIN_PATH}${MISTRAL_ARCH}-objcopy)
